### ISSUE TITLE
TypeScript declaration files are not emitted

### ISSUE THREAD

**Issue by spirosikmd** [developit/microbundle#58]
I tried the new TypeScript support in version 0.4.0 and it is awesome! Thank you!

However, I have a question regarding the declaration files. Shouldn't they be emitted as well?

*tsconfig.json*
```json
{
  "compilerOptions": {
    "target": "ES2015",
    "module": "commonjs",
    "declaration": true,
    "outDir": "dist"
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "**/*-spec.ts"]
}
```

and the output in the `dist` folder contains all files (index.js, index.m.js, index.umd.js and respective map files) except `index.d.ts`. Any idea?

**Comment by kutyel** [comment]
Having the same problem over here! https://github.com/kutyel/linq.ts/pull/107

**Comment by kutyel** [comment]
Plus, @spirosikmd how did you made that work? If I try to target `es2015` I get:
```sh
Error transforming bundle with 'uglify' plugin: Unexpected token: name (List)
```
🤔

**Comment by developit** [comment]
@kutyel using `es2015` will break uglify since it will output classes. Use `"target": "ES3"`.

Regarding the original question - why not place your `index.d.ts` in the repo root?

**Comment by spirosikmd** [comment]
@kutyel es2015 works for me. You can check this [example repository](https://github.com/spirosikmd/typescript-microbundle-example).

@developit when you say to place it in the root, do you mean running the `tsc` command just to output the declaration files? Can't `microbundle` command do this as well?

**Comment by developit** [comment]
ah - I didn't realize this was output from tsc. We should be able to extract it.

**Comment by kutyel** [comment]
@spirosikmd it only works for you because you are not using fully es2015 features (classes, arrows, etc...) if you did you'd get the same error from `uglify` I'm getting. As @developit pointed, the target needs to be `es3`. 👍 

Regarding this issue, yes, it is output that the TypeScript compilers throws and that needs to me added to the *package.json* as `"types": "dist/index.d.ts",` in order to allow people using our modules to use the typings as well 😉

**Comment by developit** [comment]
I believe this should be fixed in [0.4.3](https://github.com/developit/microbundle/releases/tag/0.4.3).

**Comment by spirosikmd** [comment]
I upgraded to 0.4.3 and the declaration files are still not emitted. I am testing with the same `tsconfig.json` as shown in my first comment.

**Comment by kutyel** [comment]
Me too, compilation targeting `es2015` is fixed, but still does not output `index.d.ts`. 😉

**Comment by kutyel** [comment]
I think https://github.com/developit/microbundle/pull/71 is ready to be merged and therefore we can release bugfix and close this issue! 👏

**Comment by developit** [comment]
merged!

**Comment by tomtobac** [comment]
Hi guys, I think the issue is still happening. I just created a small example with React & TypeScript and I doesn't create me the types. (_it could be that im doing something wrong_)

Repo example:
https://github.com/tomtobac/ti-react-components

**Comment by prztrz** [comment]
@tomtobac have you fixed this somehow? I cannot get declaration files

**Comment by spirosikmd** [comment]
@prztrz the latest version `0.11.0` emits the declaration file for me. Take a look at this [example repository](https://github.com/spirosikmd/typescript-microbundle-example). I don't see a `tsconfig.json` file in @tomtobac repo example, in which you can specify `"declaration": true`. Maybe this is the reason it wasn't working for him.

**Comment by hbroer** [comment]
`declaration true` is set within microbundle itself.

Declarations are working fine for me: [owja/ioc](https://github.com/owja/ioc)

**Comment by marvinhagemeister** [comment]
Thanks for checking again :tada: The declarations are generated for me too. Just checked with the most recent version that's on npm :+1:
