### ISSUE TITLE
Terser pure annotation stripped from build

### ISSUE THREAD

**Issue by dwightjack** [developit/microbundle#871]
Hello!

I am using a `/*#__PURE__*/ ` annotation to make a library tree shakable, but the annotation is stripped out from the build.

- Source: https://github.com/dwightjack/vue-types/blob/main/src/index.ts#L42
- command: `npx microbundle --external=vue --tsconfig=./tsconfig.build.json --format=modern`
- Build: https://unpkg.com/browse/vue-types@4.0.0/dist/vue-types.modern.js

I am probably doing something wrong. Any hint on how to fix this?

**Comment by developit** [comment]
Interesting - this should have been fixed by #848 - any chance you're ending up with an old version of Microbundle from `npx`?

**Comment by dwightjack** [comment]
Hi, thanks for your support. I've tried to remove package-lock and node_modules to refresh the package, but the problem persists.

I've created a minimal example repo here: https://github.com/dwightjack/demo-microbundle

In the `dist` folder, I see that the comment is removed from the bundled files.

> Perhaps there's a separate issue where TS is stripping the annotation.

The file in the demo repo is a plan JS file (not sure if TS parses it anyway, though).

**Comment by dwightjack** [comment]
I was trying to verify if this is a problem with terser, and I noticed that the [format.comments](https://github.com/developit/microbundle/blob/v0.13.3/src/index.js#L590) regexp might be incorrect. I think it should be:

```diff
// note the "+" after the character set
- /^\s*([@#]__[A-Z]__\s*$|@cc_on)/
+ /^\s*([@#]__[A-Z]+__\s*$|@cc_on)/
```
